### ISSUE TITLE
RespondentID is zero on survey results export

### ISSUE THREAD

**Issue by Chinthan** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS#4]
On Survey Results export all the fields of RespondentID is zero.

**Comment by Chinthan** [comment]
To get the RespondentID, we need to use 
`self.loadSurvey(surveyRef:"surveyRef" , panelID: "panelID", panellistID: "panellistID")`
method.
Need to pass `surveyRef `, `panelID `, `panellistID` for `loadSurvey`method.

Please check this [wiki link](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/wiki/03.-How-to-take-survey-with-Panellist-Authentication%3F) for detailed explanation.

**Comment by Manjunath-Ramesh** [comment]
The example code in the attached file shows how to fetch panelID and panellistID from the getPanellistPanel() api method of the SDK. 
The example code snippet for Android will be updated soon.



[TakeSurveyViewController.txt](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/files/1400974/TakeSurveyViewController.txt)

**Comment by dinesh-opg** [comment]
To get the RespondentID using android opgsdk, we need to use
super.loadOnlineSurvey(this,surveyReference,panelID,panellistID) method.
Need to pass surveyReference, panelID, panellistID for loadOnlineSurvey.

Please check this [wiki link](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/wiki/03.-How-to-take-survey-with-Panellist-Authentication%3F) for detailed explanation.

**Comment by dinesh-opg** [comment]
The example android code for fetching and loading the survey using the panelID and panellistID is attached in the below file.
[TakeSurveyActivity.txt](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/files/1401506/TakeSurveyActivity.txt)

**Comment by onepoint** [comment]
Closed
