### ISSUE TITLE
Issue with Media upload question

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS#6]
After the latest My surveys release, the app is crashing on the Medial upload question in iPhone X.

**Comment by Manjunath-Ramesh** [comment]
It is working fine here across all devices with the latest iOS 11.4 tested on iPhone 6 device and iPhone X simulator.

**Comment by dougmorris** [comment]
@onepointpb?

**Comment by pavithra-opg** [comment]
This issue no longer occurs
